apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulls-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pulls-service
  template:
    metadata:
      labels:
        app: pulls-service
    spec:
      containers:
      - name: pulls-service-container
        image: mpansuja/cloud-computing-images:pulls.0.0.1
        ports:
        - containerPort: 8100