apiVersion: apps/v1
kind: Deployment
metadata:
  name: issues-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: issues-service
  template:
    metadata:
      labels:
        app: issues-service
    spec:
      containers:
      - name: issues-service-container
        image: mpansuja/cloud-computing-images:issues.0.0.1
        ports:
        - containerPort: 8095